services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hotel
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  app:
    build: ..
    environment:
      DB_URL: jdbc:postgresql://db:5432/hotel
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 8080
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
