spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hotel}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: ${PORT:8080}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
