name: backend-ci

on:
  push:
    branches: [ main ]
    paths:
      - 'hotel-manager-backend/**'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'hotel-manager-backend/**'
      - '.github/workflows/backend-ci.yml'

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Unit tests
        run: mvn -B -f hotel-manager-backend/pom.xml test
      - name: Package
        run: mvn -B -f hotel-manager-backend/pom.xml -DskipTests package
